Revert "Add windows wheels"
This reverts commit 3cea86c5b0f4bc2037620827c8188859187b1cf0.

gnetcli fails to build for windows:

  building: go build -trimpath -ldflags=-s -w -extldflags '-static' -o C:\Users\RUNNER~1\AppData\Local\Temp\tmpxukalmwx\tmp1gz9q_od\gnetcli_server ./cmd/gnetcli_server (GOOS=windows GOARCH=amd64) cwd=C:\Users\RUNNER~1\AppData\Local\Temp\tmpxukalmwx\tmpa8e5lvy1
  go: downloading github.com/grpc-ecosystem/grpc-gateway/v2 v2.15.0
  go: downloading github.com/grpc-ecosystem/go-grpc-middleware v1.4.0
  go: downloading go.uber.org/zap v1.26.0
  go: downloading golang.org/x/sync v0.4.0
  go: downloading google.golang.org/genproto/googleapis/rpc v0.0.0-20231002182017-d307bd883b97
  go: downloading google.golang.org/grpc v1.58.2
  go: downloading google.golang.org/genproto v0.0.0-20231002182017-d307bd883b97
  go: downloading google.golang.org/genproto/googleapis/api v0.0.0-20231002182017-d307bd883b97
  go: downloading google.golang.org/protobuf v1.31.0
  go: downloading github.com/kevinburke/ssh_config v1.2.0
  go: downloading github.com/mitchellh/go-homedir v1.1.0
  go: downloading github.com/heetch/confita v0.0.0-20181011080120-653cbec9ecff
  go: downloading gopkg.in/yaml.v3 v3.0.1
  go: downloading github.com/pkg/errors v0.8.1
  go: downloading github.com/golang/protobuf v1.5.3
  go: downloading go.uber.org/multierr v1.11.0
  go: downloading golang.org/x/net v0.16.0
  go: downloading github.com/pkg/sftp v1.13.6
  go: downloading golang.org/x/crypto v0.14.0
  go: downloading github.com/BurntSushi/toml v0.3.1
  go: downloading gopkg.in/yaml.v2 v2.2.8
  go: downloading golang.org/x/exp v0.0.0-20230725093048-515e97ebf090
  go: downloading github.com/kr/fs v0.1.0
  go: downloading golang.org/x/text v0.13.0
  # github.com/annetutil/gnetcli/internal/tssh
  Error: internal\tssh\tssh.go:341:22: undefined: syscall.Socketpair
  Error: internal\tssh\tssh.go:364:17: undefined: syscall.UnixRights